### ISSUE TITLE
I am unable to connect using http url

### ISSUE THREAD

**Issue by aniketkarne** [neoatlan/nestjs-opensearch#2]
I did not find any way to disable ssl while connecting to clustor.

**Comment by neoatlan** [comment]
@aniketkarne This project is a nestjs module uses opensearch-js and the connections are established by opensearch-js.
Please ensure that which protocol is running on your opensearch server.
If your opensearch server is running on https protocol, then connecting through http protocol would not be worked.
Otherwise, please check the ssl configuration.
If your problem is a certificate problem, there is an option for validating certificate.
And it would be helpful let me know how did you launched the server and what errors are occurred.
